--TEST--
Month->distance
--FILE--
<?php

include __DIR__ . '/include.php';

foreach (time\Month::cases() as $month) {
    foreach (time\Month::cases() as $other) {
        echo $month->name . ' to ' . $other->name . ': ' . stringify($month->distance($other)) . "\n";
    }
}

--EXPECT--
January to January: 0
January to February: 1
January to March: 2
January to April: 3
January to May: 4
January to June: 5
January to July: 6
January to August: -5
January to September: -4
January to October: -3
January to November: -2
January to December: -1
February to January: -1
February to February: 0
February to March: 1
February to April: 2
February to May: 3
February to June: 4
February to July: 5
February to August: 6
February to September: -5
February to October: -4
February to November: -3
February to December: -2
March to January: -2
March to February: -1
March to March: 0
March to April: 1
March to May: 2
March to June: 3
March to July: 4
March to August: 5
March to September: 6
March to October: -5
March to November: -4
March to December: -3
April to January: -3
April to February: -2
April to March: -1
April to April: 0
April to May: 1
April to June: 2
April to July: 3
April to August: 4
April to September: 5
April to October: 6
April to November: -5
April to December: -4
May to January: -4
May to February: -3
May to March: -2
May to April: -1
May to May: 0
May to June: 1
May to July: 2
May to August: 3
May to September: 4
May to October: 5
May to November: 6
May to December: -5
June to January: -5
June to February: -4
June to March: -3
June to April: -2
June to May: -1
June to June: 0
June to July: 1
June to August: 2
June to September: 3
June to October: 4
June to November: 5
June to December: 6
July to January: 6
July to February: -5
July to March: -4
July to April: -3
July to May: -2
July to June: -1
July to July: 0
July to August: 1
July to September: 2
July to October: 3
July to November: 4
July to December: 5
August to January: 5
August to February: 6
August to March: -5
August to April: -4
August to May: -3
August to June: -2
August to July: -1
August to August: 0
August to September: 1
August to October: 2
August to November: 3
August to December: 4
September to January: 4
September to February: 5
September to March: 6
September to April: -5
September to May: -4
September to June: -3
September to July: -2
September to August: -1
September to September: 0
September to October: 1
September to November: 2
September to December: 3
October to January: 3
October to February: 4
October to March: 5
October to April: 6
October to May: -5
October to June: -4
October to July: -3
October to August: -2
October to September: -1
October to October: 0
October to November: 1
October to December: 2
November to January: 2
November to February: 3
November to March: 4
November to April: 5
November to May: 6
November to June: -5
November to July: -4
November to August: -3
November to September: -2
November to October: -1
November to November: 0
November to December: 1
December to January: 1
December to February: 2
December to March: 3
December to April: 4
December to May: 5
December to June: 6
December to July: -5
December to August: -4
December to September: -3
December to October: -2
December to November: -1
December to December: 0
